In [59]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from xgboost import XGBClassifier
from sklearn.svm import SVC

In [71]:
df = pd.read_csv("C://Users//admin//Desktop//Thyriod Detection//Data_Preprocessing//raw_data.csv")

In [72]:
df.head()

TT4         FTI  sex  on_thyroxine        T3  query_hyperthyroid  psych  \
0  125.0  109.000000    0             0  2.500000                   0      0   
1  109.0  120.000000    1             0  2.013609                   0      0   
2  175.0  110.486326    0             1  1.900000                   0      0   
3   61.0   70.000000    0             0  1.200000                   0      0   
4  183.0  141.000000    0             1  2.013609                   0      0   

   sick  tumor  pregnant  Class  
0     0      0         0      0  
1     0      0         0      0  
2     0      0         0      0  
3     0      0         0      0  
4     0      0         0      0

In [73]:
x = df.drop('Class' , axis = 1)
y = df.Class

from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.25 , random_state = 10)

# ----------------------------------------------------------------------------------------------

## RandomForest Classifier

In [74]:
rc = RandomForestClassifier()
rc.fit(x_train , y_train)
print(rc.score(x_test , y_test))
scores = cross_val_score(rc , x , y , cv = 5)
print(scores.mean())
print(scores)

0.9364889155182744
0.930777981795619
[0.86816479 0.95205993 0.94606742 0.94456929 0.94302849]


#### Confusion matrics

In [75]:
y_pred = rc.predict(x_test)
cm = confusion_matrix(y_test , y_pred)
cm

array([[782,  50],
       [ 56, 781]], dtype=int64)

# ----------------------------------------------------------------------------------------------

## XGBoost Classifier

In [76]:
xgb = XGBClassifier()
xgb.fit(x_train , y_train)
print(xgb.score(x_test , y_test))
scores = cross_val_score(xgb , x , y , cv = 5)
print(scores.mean())
print(scores)

0.9526662672258838
0.9469611261784838
[0.85093633 0.97378277 0.97453184 0.97003745 0.96551724]


####  Confusion Matrics

In [77]:
y_pred = xgb.predict(x_test)
cm = confusion_matrix(y_test , y_pred)
cm

array([[801,  31],
       [ 48, 789]], dtype=int64)

# ----------------------------------------------------------------------------------------------

## SVM Classifier

In [78]:
svm = SVC(kernel = 'linear')
svm.fit(x_train , y_train)
print(svm.score(x_test , y_test))
scores = cross_val_score(svm , x , y , cv = 5)
print(scores.mean())
print(scores)

0.7860994607549431
0.7917300900111741
[0.75505618 0.80224719 0.79475655 0.8082397  0.79835082]


####  Confusion Matrics

In [79]:
y_pred = svm.predict(x_test)
cm = confusion_matrix(y_test , y_pred)
cm

array([[626, 206],
       [151, 686]], dtype=int64)

## ---------------------------------------------------------------------------------------

## ---------------------------------------------------------------------------------------

# Conclusion

since this is a medical use case, 

so it is imporant to consider Type_2 error.

XGBoost gives the minimum type 2 error,

Also the accuracy of the model is good

hence, for this use case XGBoost will be selected.